name: Build and Distribute to Firebase

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # 3. Grants execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Decodes the keystore. THIS IS THE NEW, ROBUST METHOD.
      - name: Decode Keystore
        id: decode_keystore
        # We assign the secret to an environment variable first.
        env:
          KEYSTORE_B64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        # THEN, we check the environment variable. This avoids the parser error.
        if: env.KEYSTORE_B64 != ''
        run: |
          echo "Keystore secret found. Decoding..."
          keystore_path="${{ runner.temp }}/keystore.jks"
          # Use the environment variable in the run command.
          echo "$KEYSTORE_B64" | base64 --decode > $keystore_path
          echo "keystore_path=$keystore_path" >> $GITHUB_OUTPUT

      # 5. Builds a SIGNED release APK.
      # This step now checks if the "Decode Keystore" step SUCCEEDED.
      - name: Build with Gradle
        if: steps.decode_keystore.outcome == 'success'
        run: ./gradlew assembleRelease
        env:
          RELEASE_STORE_FILE: ${{ steps.decode_keystore.outputs.keystore_path }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      # 6. Authenticates with Google Cloud.
      # This step also only runs if the keystore was decoded successfully.
      - name: Authenticate with Google Cloud
        if: steps.decode_keystore.outcome == 'success'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIALS }}

      # 7. Uploads the signed APK to Firebase App Distribution.
      # This final step also depends on the keystore step's success.
      - name: Upload artifact to Firebase App Distribution
        if: steps.decode_keystore.outcome == 'success'
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app "${{ secrets.FIREBASE_APP_ID }}" \
            --release-notes "Build from commit ${{ github.sha }}" \
            --groups "qa-testers"